Add Dockerfile and owasp-zap scan workflow

diff --git a/.github/workflows/owasp-zap.yml b/.github/workflows/owasp-zap.yml
--- a/.github/workflows/owasp-zap.yml
+++ b/.github/workflows/owasp-zap.yml
@@ -32,10 +32,22 @@ jobs:
 
       - name: Install OWASP ZAP CLI
         run: |
-         curl -sSL https://github.com/zaproxy/zaproxy/releases/download/v2.12.0/ZAP_2.12.0_Linux.tar.gz -o zap-2.12.0-linux.tar.gz
-         tar -xzvf zap-2.12.0-linux.tar.gz
-         export ZAP_HOME=$(pwd)/zap-2.12.0
+         # Define the URL for the ZAP download
+         ZAP_URL="https://github.com/zaproxy/zaproxy/releases/download/w2025-03-04/ZAP_WEEKLY_D-2025-03-04.zip"
+
+         # Download the ZAP zip file
+         wget $ZAP_URL -O zap-weekly.zip
+
+         # Check if the download was successful
+         if [ $? -eq 0 ]; then
+         # Extract the zip file
+         unzip zap-weekly.zip -d zap-weekly
+         export ZAP_HOME=$(pwd)/zap-weekly
          export PATH=$ZAP_HOME:$PATH
+         else
+         echo "Failed to download ZAP from $ZAP_URL"
+         exit 1
+         fi
       - name: Start OWASP ZAP scan
         run: |
           zap-cli quick-scan --self-contained --start-url http://localhost:8081
